/*const marks ={
    A :"2",
    B :"3",
    C :"4"
}

for (let i = 0; i < Object.keys(marks).length; i++) {
    console.log("The marks of " +Object.keys(marks)[i]+ " are "+ marks[Object.keys(marks)[i]])
    
}

//problem 2
for(let key in marks){
    console.log("The marks of "+a+ " are ",marks[key])
}

//problem 3
let a;
while (a != 5) {
    a = prompt("Enter the number: ");
    a = Number.parseInt(a);
    if (a == 5) {
        alert("You guess the right no.");
        break;
    }
    alert("Try again");
    // let a = prompt("Enter the number: ");
}

let cn = 43
let i
while (i != cn) {
    i = prompt("Enter the number: ");
    
}
*/

//problem 4
const mean = (a,b,c,d)=>{
     return (a+b+c+d)/4;
}
console.log(mean(4,5,6,7));